INSERT IGNORE INTO Departamento (Nome) VALUES
  ('Departamento de Ciência da Computação'),
  ('Departamento de Engenharia Elétrica'),
  ('Departamento de Engenharia Mecânica'),
  ('Departamento de Engenharia Civil'),
  ('Departamento de Matemática'),
  ('Departamento de Estatística'),
  ('Departamento de Física'),
  ('Departamento de Química'),
  ('Departamento de Biologia Celular'),
  ('Departamento de Botânica'),
  ('Departamento de Zoologia'),
  ('Departamento de Psicologia Clínica'),
  ('Departamento de Psicologia Social e do Trabalho'),
  ('Departamento de Sociologia'),
  ('Departamento de Antropologia'),
  ('Departamento de História'),
  ('Departamento de Geografia'),
  ('Departamento de Letras'),
  ('Departamento de Linguística, Português e Línguas Clássicas'),
  ('Departamento de Música'),
  ('Departamento de Artes Cênicas'),
  ('Departamento de Artes Visuais'),
  ('Departamento de Comunicação'),
  ('Departamento de Jornalismo'),
  ('Departamento de Administração'),
  ('Departamento de Ciências Contábeis'),
  ('Departamento de Economia'),
  ('Departamento de Direito Público'),
  ('Departamento de Direito Privado'),
  ('Departamento de Serviço Social'),
  ('Departamento de Enfermagem'),
  ('Departamento de Farmácia'),
  ('Departamento de Medicina'),
  ('Departamento de Nutrição'),
  ('Departamento de Odontologia'),
  ('Departamento de Saúde Coletiva'),
  ('Departamento de Educação Física'),
  ('Departamento de Teoria e Fundamentos'),
  ('Departamento de Métodos e Técnicas'),
  ('Departamento de Planejamento e Administração'),
  ('Departamento de Engenharia Florestal'),
  ('Departamento de Engenharia de Produção'),
  ('Departamento de Engenharia de Software'),
  ('Departamento de Arquitetura e Urbanismo'),
  ('Departamento de Agronomia'),
  ('Departamento de Ciências Ambientais');